<a href="https://colab.research.google.com/github/kwanda2426/projects/blob/main/Mlondie_ask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
Create a dataframe with 15 participant IDs and their fitness levels (0, 1, or 2) for 14 days.

## Create the initial dataframe

### Subtask:
Create a DataFrame with 15 participant IDs and their initial randomly assigned fitness levels (0, 1, or 2).

In [2]:
import pandas as pd
import numpy as np

participant_ids = [f'Participant_{i+1}' for i in range(15)]
initial_fitness_levels = np.random.randint(0, 3, 15)

df = pd.DataFrame({
    'Participant_ID': participant_ids,
    'Initial_Fitness_Level': initial_fitness_levels
})

df_1 = df.copy()

In [3]:
import numpy as np
df_2 = df.copy()

# Define parameters for each fitness level
fitness_params = {
    0: {'mean': 6000, 'std_dev': 600},
    1: {'mean': 7500, 'std_dev': 500},
    2: {'mean': 9000, 'std_dev': 700}
}

# Generate daily step counts for 14 days
for day in range(1, 15):
    column_name = f'Steps Day {day}'

    # Create an empty list to store steps for each person
    steps = []

    # Loop through each row in df
    for level in df['Initial_Fitness_Level']:
        mean = fitness_params[level]['mean']
        std_dev = fitness_params[level]['std_dev']
        value = np.random.normal(mean, std_dev)
        value = round(value)
        value = min(max(value, 3000), 15000)  # clip between 3000 and 15000
        steps.append(int(value))

    # Add column to DataFrame
    df_2[column_name] = steps

# Display the updated DataFrame with step counts
steps_cols = [col for col in df_2.columns if 'Part' in col]+[col for col in df_2.columns if 'Steps' in col]

In [7]:
# Select the columns containing step counts
step_columns = [f'Steps Day {day}' for day in range(1, 15)]
steps_array = df_2[step_columns].values

In [4]:
# fitness assigned to each participant
display(df_1)

    Participant_ID  Initial_Fitness_Level
0    Participant_1                      2
1    Participant_2                      1
2    Participant_3                      1
3    Participant_4                      1
4    Participant_5                      0
5    Participant_6                      1
6    Participant_7                      1
7    Participant_8                      1
8    Participant_9                      0
9   Participant_10                      2
10  Participant_11                      2
11  Participant_12                      1
12  Participant_13                      1
13  Participant_14                      0
14  Participant_15                      0

In [8]:
display(df_2[steps_cols])

,Participant_ID,Steps Day 1,Steps Day 2,Steps Day 3,Steps Day 4,Steps Day 5,Steps Day 6,Steps Day 7,Steps Day 8,Steps Day 9,Steps Day 10,Steps Day 11,Steps Day 12,Steps Day 13,Steps Day 14
0,Participant_1,9518,8426,8607,8669,9583,8772,8641,8541,7776,9720,9352,8931,9203,8509
1,Participant_2,6860,7689,7378,7896,7522,7910,7520,8160,7440,6868,7660,7966,7204,7666
2,Participant_3,8064,6942,8760,7806,6501,6940,7798,7591,7272,7670,7612,7982,7160,7482
3,Participant_4,7905,7723,7937,8144,7748,7250,7230,7809,7117,8042,7857,6762,8151,7680
4,Participant_5,6280,7377,5682,6058,6021,6430,4397,7045,6881,7136,5183,5634,6071,5703
5,Participant_6,7689,8052,7676,6828,8033,8099,7521,7586,8387,7540,7575,6587,7993,6987
6,Participant_7,7525,7316,7553,8006,8312,7552,7608,6244,7340,7180,7374,8053,7040,7105
7,Participant_8,7546,8009,7523,7991,7556,7247,7930,7425,7654,7843,7083,6774,8105,7350
8,Participant_9,6428,6606,5690,6217,4980,5126,6065,6540,5701,5492,5303,5640,6448,6691
9,Participant_10,9403,8965,9479,9895,8776,8575,9215,9107,7872,7765,9182,8095,9301,7943
10,Participant_11,9802,8273,7717,9827,9388,7914,7558,8425,9559,8854,7904,8117,8788,8912
11,Participant_12,7006,7281,8498,8403,7650,8076,6925,7366,7766,7866,7671,7626,8260,7106
12,Participant_13,7745,7506,7669,8088,7426,7549,6886,7253,8083,7873,6690,7045,7324,7769
13,Participant_14,5556,5589,5889,6214,6841,6116,5403,6784,5642,5990,6328,6120,6349,6924
14,Participant_15,5892,5609,5331,5415,7053,5783,6615,5115,6398,5048,6515,6236,6769,5947

In [9]:
# Calculate the average daily steps for each participant
df_2['Average_Daily_Steps'] = df_2[step_columns].mean(axis=1)

# Sort the participants by average daily steps in descending order
df_sorted = df_2.sort_values(by='Average_Daily_Steps', ascending=False)

# Display the top 5 participants and their average daily steps
display(df_sorted[['Participant_ID', 'Average_Daily_Steps']].head())

    Participant_ID  Average_Daily_Steps
0    Participant_1          8874.857143
9   Participant_10          8826.642857
10  Participant_11          8645.571429
11  Participant_12          7678.571429
3    Participant_4          7668.214286