<a href="https://colab.research.google.com/github/kwanda2426/projects/blob/main/Mlondie_ask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Question 2 - Part 1: Dataset Creation

Create a DataFrame with 15 participant IDs and their initial randomly assigned fitness levels (Low : 0, Moderate: 1, or High: 2).

In [1]:
import warnings
import pandas as pd
import numpy as np

# Ignore all warnings
warnings.filterwarnings("ignore")

In [2]:

participant_ids = [f'Participant_{i+1}' for i in range(15)]
initial_fitness_levels = np.random.randint(0, 3, 15)

df = pd.DataFrame({
    'Participant_ID': participant_ids,
    'Initial_Fitness_Level': initial_fitness_levels
})

df_1 = df.copy()

In [3]:
import numpy as np
df_2 = df.copy()

# Define parameters for each fitness level
fitness_params = {
    0: {'mean': 6000, 'std_dev': 600},
    1: {'mean': 7500, 'std_dev': 500},
    2: {'mean': 9000, 'std_dev': 700}
}

# Generate daily step counts for 14 days
for day in range(1, 15):
    column_name = f'Steps Day {day}'

    # Create an empty list to store steps for each person
    steps = []

    # Loop through each row in df
    for level in df['Initial_Fitness_Level']:
        mean = fitness_params[level]['mean']
        std_dev = fitness_params[level]['std_dev']
        value = np.random.normal(mean, std_dev)
        value = round(value)
        value = min(max(value, 3000), 15000)  # clip between 3000 and 15000
        steps.append(int(value))

    # Add column to DataFrame
    df_2[column_name] = steps

# Display the updated DataFrame with step counts
steps_cols = [col for col in df_2.columns if 'Part' in col]+[col for col in df_2.columns if 'Steps' in col]

In [4]:
# Select the columns containing step counts
step_columns = [f'Steps Day {day}' for day in range(1, 15)]
steps_array = df_2[step_columns].values

In [5]:
# fitness assigned to each participant
display(df_1)

    Participant_ID  Initial_Fitness_Level
0    Participant_1                      1
1    Participant_2                      0
2    Participant_3                      1
3    Participant_4                      0
4    Participant_5                      2
5    Participant_6                      1
6    Participant_7                      2
7    Participant_8                      2
8    Participant_9                      1
9   Participant_10                      1
10  Participant_11                      2
11  Participant_12                      0
12  Participant_13                      0
13  Participant_14                      2
14  Participant_15                      0

In [6]:
display(df_2[steps_cols])

,Participant_ID,Steps Day 1,Steps Day 2,Steps Day 3,Steps Day 4,Steps Day 5,Steps Day 6,Steps Day 7,Steps Day 8,Steps Day 9,Steps Day 10,Steps Day 11,Steps Day 12,Steps Day 13,Steps Day 14
0,Participant_1,7075,8730,7014,6864,7005,6952,8218,7463,7442,7732,7317,6908,7078,7255
1,Participant_2,6273,7291,6232,5763,6618,5966,6073,6948,6634,6121,6184,6302,6411,5595
2,Participant_3,7545,7875,7395,7739,7781,7395,7442,7393,7665,6933,6874,6770,7629,6862
3,Participant_4,4651,7079,6145,5341,5533,6610,6479,6570,5841,6050,7029,6529,6196,6554
4,Participant_5,8356,9115,10384,9561,9790,8824,8837,9360,9974,9909,9286,9931,8811,9154
5,Participant_6,7931,8431,7563,7259,7039,7045,7346,7058,6666,7434,7094,6412,8331,6725
6,Participant_7,9187,8219,8458,8250,8231,9585,9018,9320,9001,9436,8496,8797,8229,9371
7,Participant_8,8194,9186,9556,8630,9657,8797,8963,8672,8764,7810,9593,10290,9266,8927
8,Participant_9,7238,7577,7476,7174,7259,7495,7389,7881,7262,6741,8258,7339,7360,8551
9,Participant_10,7105,7710,7060,7435,7789,6586,7084,7462,8269,7567,7640,7230,7633,8353
10,Participant_11,8128,8728,8752,10185,8290,8959,8197,8776,8861,10186,8492,9061,8747,10897
11,Participant_12,5864,5198,6086,5096,6564,6113,5598,6954,6028,5282,5423,5595,7046,6474
12,Participant_13,6354,5457,6148,5614,5758,6862,5944,5328,5787,6199,6613,6562,5316,6075
13,Participant_14,9182,8206,8776,8444,8406,9051,8227,9057,8811,9049,7884,9914,8910,9218
14,Participant_15,6033,7918,6396,6086,5622,5749,6729,7132,5894,6112,6726,5233,6725,6221

## Question 2 - Part 2: Data Analysis

In [7]:
# Calculate the average daily steps for each participant
df_2['Average_Daily_Steps'] = df_2[step_columns].mean(axis=1)

# Sort the participants by average daily steps in descending order
df_sorted = df_2.sort_values(by='Average_Daily_Steps', ascending=False)

# Display the top 5 participants and their average daily steps
display(df_sorted[['Participant_ID', 'Average_Daily_Steps']].head())

    Participant_ID  Average_Daily_Steps
4    Participant_5          9378.000000
7    Participant_8          9021.785714
10  Participant_11          9018.500000
6    Participant_7          8828.428571
13  Participant_14          8795.357143

In [8]:
# Overall mean and standard deviation of all step counts
overall_mean_steps = round(steps_array.mean())
overall_std_steps = round(steps_array.std())

# Display overall mean and standard deviation
print(f'Overall Mean Steps: {overall_mean_steps}')
print(f'Overall Standard Deviation Steps: {overall_std_steps}')

Overall Mean Steps: 7524
Overall Standard Deviation Steps: 1301

In [9]:
# Median daily steps for each participant
df_2['Median_Daily_Steps'] = df_2[step_columns].median(axis=1)

# Participants with the highest median daily steps
highest_median_steps = df_2['Median_Daily_Steps'].max()
participants_highest_median = df_2[df_2['Median_Daily_Steps'] == highest_median_steps][['Participant_ID', 'Median_Daily_Steps']]

# Participant with the lowest median daily steps
lowest_median_steps = df_2['Median_Daily_Steps'].min()
participants_lowest_median = df_2[df_2['Median_Daily_Steps'] == lowest_median_steps][['Participant_ID', 'Median_Daily_Steps']]

# Display the participant with the highest median daily steps
print("Participant(s) with the Highest Median Daily Steps:")
display(participants_highest_median)

# Display the participant with the lowest median daily steps
print("\nParticipant(s) with the Lowest Median Daily Steps:")
display(participants_lowest_median)

Participant(s) with the Highest Median Daily Steps:

  Participant_ID  Median_Daily_Steps
4  Participant_5              9323.0

Participant(s) with the Lowest Median Daily Steps:

    Participant_ID  Median_Daily_Steps
11  Participant_12              5946.0

In [10]:
# Count participants with average daily steps above 8000
participants_above_8000 = df_sorted[df_sorted['Average_Daily_Steps'] > 8000]
count_above_8000 = len(participants_above_8000)

# Display the count
print(f'Number of participants with average daily steps above 8000: {count_above_8000}')

Number of participants with average daily steps above 8000: 5

In [11]:
# Compute the percentiles
percentiles = np.percentile(steps_array, [25, 50, 75])

# Display the percentiles
print(f"25th Percentile: {round(percentiles[0])}")
print(f"50th Percentile (Median): {round(percentiles[1])}")
print(f"75th Percentile: {round(percentiles[2])}")

25th Percentile: 6562
50th Percentile (Median): 7394
75th Percentile: 8610

## Question 3 - Part 1: Dataset Preparation and Cleaning

In [12]:
# Load data from Github
url = "https://raw.githubusercontent.com/kwanda2426/projects/main/adult.csv"
input_data = pd.read_csv(url)
input_data.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [13]:
input_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [14]:
# Replace . with _ column names
input_data.columns = input_data.columns.str.replace('.', '_', regex=False)

In [15]:
# Columns with ? as missing values and their count
(input_data == "?").sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [16]:
input_data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [17]:
input_data.replace("?", np.nan, inplace=True)

In [18]:
df = input_data.copy()

In [19]:
# Separate columns by data type
categorical_cols = df.select_dtypes(include = ["object"]).columns
numerical_cols = df.select_dtypes(include = [np.number]).columns

In [20]:
# Separate columns by data type
categorical_cols = df.select_dtypes(include = ["object"]).columns
numerical_cols = df.select_dtypes(include = [np.number]).columns

# Impute categorical columns with mode (most frequent value)
for col in categorical_cols:
    mode_value = df[col].mode()[0]
    df[col].fillna(mode_value, inplace=True)

# Impute numerical columns with median
for col in numerical_cols:
    median_value = df[col].median()
    df[col].fillna(median_value, inplace=True)

In [21]:
# check that no missing values remain
print(input_data.isnull().sum())

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64