## ** Royal Draconic Conservatory ** -

<div style="text-align: center;">
   <img src="https://raw.githubusercontent.com/kwanda2426/ACML_26_P1/main/Models/card_risk.png"  width="800">
</div>

# **Importing Libraries**

In [1]:
!pip -q install plotly scikit-learn tabulate pandas gdown

In [2]:
# Libraries for data loading, data manipulation and data visulisation
import numpy as np
import pandas as pd

import gdown

import matplotlib.pyplot as plt
from matplotlib import rc
import seaborn as sns
import plotly.express as px
from scipy.stats import kurtosis


#Feature engineering, selection and Model training
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.multioutput import MultiOutputRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


#ignoring warnings
import warnings
warnings.filterwarnings('ignore')

#making sure that we can see all rows and cols
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
from tabulate import tabulate
from IPython.display import display

# **Data acquisition**

#### Main Data

In [3]:
# Reading and downloading from drive
file_id = "1deTfwvspgT545M_-ZCkHU4RqQl_b1jzp"
url = f"https://drive.google.com/uc?id={file_id}"

output = "data.csv"
gdown.download(url, output, quiet = False)

Downloading...
From (original): https://drive.google.com/uc?id=1deTfwvspgT545M_-ZCkHU4RqQl_b1jzp
From (redirected): https://drive.google.com/uc?id=1deTfwvspgT545M_-ZCkHU4RqQl_b1jzp&confirm=t&uuid=ab57c230-9d8d-4bab-aa98-1d74eee79b09
To: /content/data.csv
100%|██████████| 166M/166M [00:02<00:00, 82.9MB/s]

'data.csv'

In [4]:
# reading into a dataframe
df_main = pd.read_csv(output)
df_main.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

#### Column Discription

In [5]:
def github_to_raw(url):
    return url.replace("github.com", "raw.githubusercontent.com") \
              .replace("/blob/", "/")

url = "https://github.com/kwanda2426/ACML_26_P1/blob/main/Datasets/columns_description.csv"

raw_url = github_to_raw(url)


df_desc = pd.read_csv(raw_url, encoding="cp1252", encoding_errors="replace")
df_desc = df_desc[df_desc['Table'] == 'application_data'][['Table',	'Row',	'Description',	'Special']]
df_desc.head(10)

,Table,Row,Description,Special
0,application_data,SK_ID_CURR,ID of loan in our sample,NaN
1,application_data,TARGET,"Target variable (1 - client with payment difficulties: he/she had late payment more than X days on at least one of the first Y installments of the loan in our sample, 0 - all other cases)",NaN
2,application_data,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,application_data,CODE_GENDER,Gender of the client,NaN
4,application_data,FLAG_OWN_CAR,Flag if the client owns a car,NaN
5,application_data,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN
6,application_data,CNT_CHILDREN,Number of children the client has,NaN
7,application_data,AMT_INCOME_TOTAL,Income of the client,NaN
8,application_data,AMT_CREDIT,Credit amount of the loan,NaN
9,application_data,AMT_ANNUITY,Loan annuity,NaN

# **Data Preprocessing**

Data preprocessing is vital because it transforms messy raw data into a clean, consistent, and structured format, which is essential for accurate analysis and effective machine learning models.
Issues like missing values, inconsistencies, errors, and outliers are addressed to improve data quality,leads to more reliable and meaningful insights for decision-making and ultimately enhances the performance and accuracy of models.

#### Reviewing and Renaming Columns

In [6]:
# data columns
df_main.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

- There are column names that have UPPERCASE. All variable names are converted to lowercase.

In [7]:
# Changing column names
df_main.columns = df_main.columns.str.replace(' ', '_', regex=False).str.lower()
df_main.head()

,sk_id_curr,target,name_contract_type,code_gender,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_type_suite,name_income_type,name_education_type,name_family_status,name_housing_type,region_population_relative,days_birth,days_employed,days_registration,days_id_publish,own_car_age,flag_mobil,flag_emp_phone,flag_work_phone,flag_cont_mobile,flag_phone,flag_email,occupation_type,cnt_fam_members,region_rating_client,region_rating_client_w_city,weekday_appr_process_start,hour_appr_process_start,reg_region_not_live_region,reg_region_not_work_region,live_region_not_work_region,reg_city_not_live_city,reg_city_not_work_city,live_city_not_work_city,organization_type,ext_source_1,ext_source_2,ext_source_3,apartments_avg,basementarea_avg,years_beginexpluatation_avg,years_build_avg,commonarea_avg,elevators_avg,entrances_avg,floorsmax_avg,floorsmin_avg,landarea_avg,livingapartments_avg,livingarea_avg,nonlivingapartments_avg,nonlivingarea_avg,apartments_mode,basementarea_mode,years_beginexpluatation_mode,years_build_mode,commonarea_mode,elevators_mode,entrances_mode,floorsmax_mode,floorsmin_mode,landarea_mode,livingapartments_mode,livingarea_mode,nonlivingapartments_mode,nonlivingarea_mode,apartments_medi,basementarea_medi,years_beginexpluatation_medi,years_build_medi,commonarea_medi,elevators_medi,entrances_medi,floorsmax_medi,floorsmin_medi,landarea_medi,livingapartments_medi,livingarea_medi,nonlivingapartments_medi,nonlivingarea_medi,fondkapremont_mode,housetype_mode,totalarea_mode,wallsmaterial_mode,emergencystate_mode,obs_30_cnt_social_circle,def_30_cnt_social_circle,obs_60_cnt_social_circle,def_60_cnt_social_circle,days_last_phone_change,flag_document_2,flag_document_3,flag_document_4,flag_document_5,flag_document_6,flag_document_7,flag_document_8,flag_document_9,flag_document_10,flag_document_11,flag_document_12,flag_document_13,flag_document_14,flag_document_15,flag_document_16,flag_document_17,flag_document_18,flag_document_19,flag_document_20,flag_document_21,amt_req_credit_bureau_hour,amt_req_credit_bureau_day,amt_req_credit_bureau_week,amt_req_credit_bureau_mon,amt_req_credit_bureau_qrt,amt_req_credit_bureau_year
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

#### Dataset Dimensions and Variable Type

In [8]:
df = df_main.copy()

In [12]:
# Rows and Columns of data
print('Data has {} rows and {} Columns'.format(df.shape[0],df.shape[1]))
print('')
print('Data has the following variables with missing values:')
print('')
major_missing = []
for i in df.columns:
  missing_values = 100*df[i].isnull().sum()/df.shape[0]
  if missing_values > 0:
    print(i+', with {}% of missing data'.format(missing_values))
    if missing_values > 30:
      major_missing.append(i)

Data has 307511 rows and 122 Columns

Data has the following variables with missing values:

amt_annuity, with 0.0039022994299390914% of missing data
amt_goods_price, with 0.09040327012692229% of missing data
name_type_suite, with 0.42014757195677555% of missing data
own_car_age, with 65.9908100848425% of missing data
occupation_type, with 31.345545362604916% of missing data
cnt_fam_members, with 0.000650383238323182% of missing data
ext_source_1, with 56.38107254699832% of missing data
ext_source_2, with 0.21462646864665003% of missing data
ext_source_3, with 19.825307062186393% of missing data
apartments_avg, with 50.749729277977046% of missing data
basementarea_avg, with 58.515955526794166% of missing data
years_beginexpluatation_avg, with 48.781019215572776% of missing data
years_build_avg, with 66.49778381911541% of missing data
commonarea_avg, with 69.87229725115525% of missing data
elevators_avg, with 53.29597965601231% of missing data
entrances_avg, with 50.34876801155081% of missing data
floorsmax_avg, with 49.76082156410665% of missing data
floorsmin_avg, with 67.84862980511267% of missing data
landarea_avg, with 59.376737742714894% of missing data
livingapartments_avg, with 68.35495315614726% of missing data
livingarea_avg, with 50.193326417591564% of missing data
nonlivingapartments_avg, with 69.43296337366793% of missing data
nonlivingarea_avg, with 55.17916432257708% of missing data
apartments_mode, with 50.749729277977046% of missing data
basementarea_mode, with 58.515955526794166% of missing data
years_beginexpluatation_mode, with 48.781019215572776% of missing data
years_build_mode, with 66.49778381911541% of missing data
commonarea_mode, with 69.87229725115525% of missing data
elevators_mode, with 53.29597965601231% of missing data
entrances_mode, with 50.34876801155081% of missing data
floorsmax_mode, with 49.76082156410665% of missing data
floorsmin_mode, with 67.84862980511267% of missing data
landarea_mode, with 59.376737742714894% of missing data
livingapartments_mode, with 68.35495315614726% of missing data
livingarea_mode, with 50.193326417591564% of missing data
nonlivingapartments_mode, with 69.43296337366793% of missing data
nonlivingarea_mode, with 55.17916432257708% of missing data
apartments_medi, with 50.749729277977046% of missing data
basementarea_medi, with 58.515955526794166% of missing data
years_beginexpluatation_medi, with 48.781019215572776% of missing data
years_build_medi, with 66.49778381911541% of missing data
commonarea_medi, with 69.87229725115525% of missing data
elevators_medi, with 53.29597965601231% of missing data
entrances_medi, with 50.34876801155081% of missing data
floorsmax_medi, with 49.76082156410665% of missing data
floorsmin_medi, with 67.84862980511267% of missing data
landarea_medi, with 59.376737742714894% of missing data
livingapartments_medi, with 68.35495315614726% of missing data
livingarea_medi, with 50.193326417591564% of missing data
nonlivingapartments_medi, with 69.43296337366793% of missing data
nonlivingarea_medi, with 55.17916432257708% of missing data
fondkapremont_mode, with 68.38617155158677% of missing data
housetype_mode, with 50.176091261776% of missing data
totalarea_mode, with 48.26851722377411% of missing data
wallsmaterial_mode, with 50.8407829313423% of missing data
emergencystate_mode, with 47.39830445089769% of missing data
obs_30_cnt_social_circle, with 0.3320206431639844% of missing data
def_30_cnt_social_circle, with 0.3320206431639844% of missing data
obs_60_cnt_social_circle, with 0.3320206431639844% of missing data
def_60_cnt_social_circle, with 0.3320206431639844% of missing data
days_last_phone_change, with 0.000325191619161591% of missing data
amt_req_credit_bureau_hour, with 13.501630835970095% of missing data
amt_req_credit_bureau_day, with 13.501630835970095% of missing data
amt_req_credit_bureau_week, with 13.501630835970095% of missing data
amt_req_credit_bureau_mon, with 13.501630835970095% of missing data
amt_req_credit_bureau_qrt, with 13.501630835970095% of missing data
amt_req_credit_bureau_year, with 13.501630835970095% of missing data

In [76]:
len(major_missing)

50

In [44]:
cols_unneeded1 = [i for i in df.columns if 'flag' in i] + [i for i in df.columns if 'social' in i] + [i for i in df.columns if 'region' in i]+ [i for i in df.columns if 'process' in i]
cols_unneeded2 = [i for i in df.columns if 'id' in i]+ [i for i in df.columns if 'source' in i]+ [i for i in df.columns if 'bureau' in i] + [i for i in df.columns if 'city' in i]
cols_unneeded3 = [i for i in df.columns if 'days' in i]

final_cols = major_missing+cols_unneeded1+cols_unneeded2+cols_unneeded3

In [45]:
df_fin = df.drop(final_cols, axis = 1)

In [46]:
df_fin.columns

Index(['target', 'name_contract_type', 'code_gender', 'cnt_children',
       'amt_income_total', 'amt_credit', 'amt_annuity', 'amt_goods_price',
       'name_type_suite', 'name_income_type', 'name_education_type',
       'name_family_status', 'name_housing_type', 'cnt_fam_members',
       'organization_type'],
      dtype='object')

#### Summary Statistics and Variable Description

In [47]:
#describing numerical columns
df_fin.describe().T

,count,mean,std,min,25%,50%,75%,max
target,307511.0,0.080729,0.272419,0.0,0.0,0.0,0.0,1.0
cnt_children,307511.0,0.417052,0.722121,0.0,0.0,0.0,1.0,19.0
amt_income_total,307511.0,168797.919297,237123.146279,25650.0,112500.0,147150.0,202500.0,117000000.0
amt_credit,307511.0,599025.999706,402490.776996,45000.0,270000.0,513531.0,808650.0,4050000.0
amt_annuity,307499.0,27108.573909,14493.737315,1615.5,16524.0,24903.0,34596.0,258025.5
amt_goods_price,307233.0,538396.207429,369446.460540,40500.0,238500.0,450000.0,679500.0,4050000.0
cnt_fam_members,307509.0,2.152665,0.910682,1.0,2.0,2.0,3.0,20.0

In [48]:
df_fin.name_contract_type.value_counts()

name_contract_type
Cash loans         278232
Revolving loans     29279
Name: count, dtype: int64

In [49]:
df_fin[df_fin.name_contract_type == 'Cash loans'].target.value_counts()

target
0    255011
1     23221
Name: count, dtype: int64

In [50]:
df_fin[df_fin.name_contract_type == 'Revolving loans'].target.value_counts()

target
0    27675
1     1604
Name: count, dtype: int64

# **Feature Engineering**

This is a vital step where data is explored and then transformed from raw data into features that enhance machine learning model performance, accuracy, and generalization by making patterns more discernable.

### **Exploratory Data Analysis**

This method is meant to uncover the underlying structure of a data set and is important for a company because it exposes trends, patterns, and relationships that are not readily apparent.

#### **Distributions**
This is meant to discover :
- Distribution of features to decide on the kind of scaling required

#### sub

In [ ]:
#df_temp = df.copy()
#plt.figure(figsize = (10,8))
#sns.heatmap(df_temp.corr(), annot = True,cmap = 'coolwarm' )
#plt.title('Feature Correlation Heatmap')
#plt.show()

In [ ]:
#df_temp.corr()

These features exhibit heavy-tailed distributions (kurtosis > 3), indicating high outlier risk, so a scaler robust to outliers is needed. The RobustScaler would be suitable for feature scaling.

#### Feature Scaling

it prevents features with larger numerical values from disproportionately influencing the model's learning.
When features have vastly different ranges (e.g., one feature ranges from 0-10 and another from 0-10,000), the model can become biased toward the feature with the larger magnitude, simply because its values are larger.

In [ ]:
#df.head()

In [ ]:
# features and target variable
#df_final = df.copy()


# Initialize the scaler
#scaler = RobustScaler()
# apply scaler to predictor variables
#X_scaled = scaler.fit_transform(X)

#### Data Split
Splitting data into training and testing sets is essential to evaluate a model's performance on new, unseen data and prevent overfitting. The training set teaches the model patterns, while the untouched test set provides an unbiased assessment of its generalisation ability, ensuring the model performs accurately in real-world scenarios rather than just on the data it learned from.

In [ ]:
 # Train- test Split: 80% train and 20% test -- random state = 42, ensure the reproducibility of the data split
#X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, random_state = 42)

# **Model selection**

A hybrid deep learning architecture was implemented consisting of a stacked autoencoder for unsupervised feature representation learning followed by a feedforward neural network classifier. The autoencoder reduces the high-dimensional feature space into a compact latent embedding, capturing nonlinear interactions among financial variables. The classifier is composed of fully connected layers with ReLU activation, batch normalization, and dropout regularization to prevent overfitting. The model is trained in two stages: (1) unsupervised reconstruction pretraining and (2) supervised fine-tuning for binary classification using binary cross-entropy loss.

1. ****
 :  

 2. **** :

 3. **** :

# **Model Training and Evaluation**

In this step, data is training data fed to the model. Training a model is essential because it allows the algorithm to learn patterns and relationships from data so it can make accurate predictions or decisions on new, unseen inputs. Without training, the model would have no understanding of how features relate to outcomes.

evaluation

In [62]:
df_fin.head()

,target,name_contract_type,code_gender,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,name_type_suite,name_income_type,name_education_type,name_family_status,name_housing_type,cnt_fam_members,organization_type
0,1,Cash loans,M,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,1.0,Business Entity Type 3
1,0,Cash loans,F,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,2.0,School
2,0,Revolving loans,M,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,1.0,Government
3,0,Cash loans,F,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,2.0,Business Entity Type 3
4,0,Cash loans,M,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,1.0,Religion

In [63]:
numeric_df = df_fin.select_dtypes(include='number')
numeric_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   target            307511 non-null  int64
 1   cnt_children      307511 non-null  int64
 2   amt_income_total  307511 non-null  float64
 3   amt_credit        307511 non-null  float64
 4   amt_annuity       307499 non-null  float64
 5   amt_goods_price   307233 non-null  float64
 6   cnt_fam_members   307509 non-null  float64
dtypes: float64(5), int64(2)
memory usage: 16.4 MB

In [64]:
df = numeric_df.dropna(axis=0)

In [65]:
df.head()

,target,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,cnt_fam_members
0,1,0,202500.0,406597.5,24700.5,351000.0,1.0
1,0,0,270000.0,1293502.5,35698.5,1129500.0,2.0
2,0,0,67500.0,135000.0,6750.0,135000.0,1.0
3,0,0,135000.0,312682.5,29686.5,297000.0,2.0
4,0,0,121500.0,513000.0,21865.5,513000.0,1.0

BASE LINE Model

In [66]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

In [67]:
X = df.drop(columns=["target"])
y = df["target"]

# basic imputation
imputer = SimpleImputer(strategy="median")
X = imputer.fit_transform(X)

# scaling for NN (important)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

In [68]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss"
)

xgb_model.fit(X_train, y_train)
xgb_train_pred = xgb_model.predict_proba(X_train)[:, 1]
xgb_test_pred = xgb_model.predict_proba(X_test)[:, 1]

In [69]:
import torch
import torch.nn as nn

In [70]:
class TabularNN(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.BatchNorm1d(128),
            nn.Dropout(0.3),

            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.2),

            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)

In [71]:
X_train_t = torch.tensor(X_train, dtype=torch.float32)
y_train_t = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)

model = TabularNN(X_train.shape[1])
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(20):
    model.train()

    preds = model(X_train_t)
    loss = criterion(preds, y_train_t)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [72]:
model.eval()
with torch.no_grad():
    nn_train_pred = model(X_train_t).numpy().flatten()
    nn_test_pred = model(torch.tensor(X_test, dtype=torch.float32)).numpy().flatten()

Stacking Results

In [73]:
import numpy as np

stacked_train = np.column_stack((xgb_train_pred, nn_train_pred))
stacked_test = np.column_stack((xgb_test_pred, nn_test_pred))

In [74]:
from sklearn.linear_model import LogisticRegression

meta_model = LogisticRegression()
meta_model.fit(stacked_train, y_train)

final_pred = meta_model.predict_proba(stacked_test)[:, 1]

In [75]:
from sklearn.metrics import roc_auc_score, accuracy_score

print("AUC:", roc_auc_score(y_test, final_pred))
print("Accuracy:", accuracy_score(y_test, final_pred > 0.5))

AUC: 0.6385836345247766
Accuracy: 0.9185613149971519

XGBoost contributes:
handles nonlinearity well
strong on tabular + missing patterns
captures feature interactions explicitly
 Neural Network contributes:
learns dense latent representations
captures smooth nonlinear boundaries
generalizes differently from trees
Stacking layer contributes:
learns optimal combination of both models
reduces overfitting from single model bias
improves calibration of probabilities

# **Model Evaluation Results**

Models are evaluated using the validation dataset. Validating these trained models is crucial because it helps identify which one performs best to unseen data—without touching the test set. This step acts like a rehearsal before the final performance: it reveals whether the model is overfitting (memorising the training data) or underfitting (failing to learn enough). By evaluating on the validation set, we can select the most promising model and fine-tune its hyperparameters, ensuring that when it is finally tested, the true predictive power is measured — not just luck or overtraining.

### ** Evaluation Metrics**

In [ ]:
# Evaluation Results
#print(tabulate(results_df, headers='keys', tablefmt='grid'))